import { Router, type IRouter } from "express";
import healthRouter from "./health";
import characterRouter from "./character";
import journalEntriesRouter from "./journal-entries";
import storiesRouter from "./stories";
import outfitsRouter from "./outfits";
import galleryRouter from "./gallery";
import uploadRouter from "./upload";
import socialRouter from "./social";
import notificationsRouter from "./notifications";
import weatherRouter from "./weather";
import reportsRouter from "./reports";
import adminRouter from "./admin";
import guidesRouter from "./guides";
import messagesRouter from "./messages";
import driftRouter from "./drift";
import stickersRouter from "./stickers";
import rewardsRouter from "./rewards";

const router: IRouter = Router();

router.use(healthRouter);
router.use(characterRouter);
router.use(journalEntriesRouter);
router.use(storiesRouter);
router.use(outfitsRouter);
router.use(galleryRouter);
router.use(uploadRouter);
router.use(socialRouter);
router.use(notificationsRouter);
router.use(weatherRouter);
router.use(reportsRouter);
router.use(adminRouter);
router.use(guidesRouter);
router.use(messagesRouter);
router.use(driftRouter);
router.use(stickersRouter);
router.use(rewardsRouter);

export default router;
