import { Router, type IRouter } from "express";
import healthRouter from "./health";
import characterRouter from "./character";
import journalEntriesRouter from "./journal-entries";
import storiesRouter from "./stories";
import outfitsRouter from "./outfits";
import galleryRouter from "./gallery";
import uploadRouter from "./upload";
import socialRouter from "./social";
import notificationsRouter from "./notifications";
import weatherRouter from "./weather";
import reportsRouter from "./reports";
import adminRouter from "./admin";
import guidesRouter from "./guides";
import messagesRouter from "./messages";
import driftRouter from "./drift";
import stickersRouter from "./stickers";
import rewardsRouter from "./rewards";
import adminEventsRouter from "./admin-events";
import adminProfileEffectsRouter from "./admin-profile-effects";
import adminSettingsRouter from "./admin-settings";
import adminNotificationsRouter from "./admin-notifications";
import campfireRouter from "./campfire";
import streamRouter from "./stream";
import pushRouter from "./push";
import adminBadgesRouter from "./admin-badges";
import blocksRouter from "./blocks";
import booksRouter from "./books";
import bookReaderRouter from "./book-reader";
import creatorDashboardRouter from "./creator-dashboard";
import aiAssistRouter from "./ai-assist";
import mangaGenerationRouter from "./manga-generation";
import musicRouter from "./music";
import mediaRouter from "./media";

const router: IRouter = Router();

router.use(healthRouter);
router.use(characterRouter);
router.use(journalEntriesRouter);
router.use(storiesRouter);
router.use(outfitsRouter);
router.use(galleryRouter);
router.use(uploadRouter);
router.use(socialRouter);
router.use(notificationsRouter);
router.use(weatherRouter);
router.use(reportsRouter);
router.use(adminRouter);
router.use(guidesRouter);
router.use(messagesRouter);
router.use(driftRouter);
router.use(stickersRouter);
router.use(rewardsRouter);
router.use(adminEventsRouter);
router.use(adminProfileEffectsRouter);
router.use(adminSettingsRouter);
router.use(adminNotificationsRouter);
router.use(campfireRouter);
router.use(streamRouter);
router.use(pushRouter);
router.use(adminBadgesRouter);
router.use(blocksRouter);
router.use(booksRouter);
router.use(bookReaderRouter);
router.use(creatorDashboardRouter);
router.use(aiAssistRouter);
router.use(mangaGenerationRouter);
router.use(musicRouter);
router.use(mediaRouter);

export default router;
