/**
 * Drop-in replacement for @expo/vector-icons Feather.
 * Uses lucide-react-native (SVG-based) — no font file needed.
 * Font-based icons were unreliable in Expo Go on Android (New Architecture).
 *
 * Usage:  <Icon name="home" size={20} color="#fff" />
 */
import {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Bell,
  BellOff,
  Bookmark,
  Book,
  BookOpen,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CirclePlus,
  Clock,
  Cloud,
  Compass,
  Crop,
  Droplet,
  Eye,
  EyeOff,
  Feather,
  FileText,
  Flag,
  Globe,
  Grid3x3,
  Heart,
  Home,
  Image as ImageIcon,
  Key,
  LayoutGrid,
  Layers,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  MessageCircle,
  Minus,
  Monitor,
  Moon,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Shield,
  Slash,
  SlidersHorizontal,
  Smile,
  Star,
  Sun,
  Sunrise,
  Trash2,
  TrendingUp,
  User,
  Users,
  Wind,
  X,
  Zap,
  type LucideProps,
} from 'lucide-react-native';
import React from 'react';

const ICON_MAP = {
  'alert-circle':  AlertCircle,
  'arrow-down':    ArrowDown,
  'arrow-left':    ArrowLeft,
  'arrow-right':   ArrowRight,
  'bell':          Bell,
  'bell-off':      BellOff,
  'book':          Book,
  'book-open':     BookOpen,
  'bookmark':      Bookmark,
  'calendar':      Calendar,
  'camera':        Camera,
  'check':         Check,
  'check-circle':  CheckCircle,
  'chevron-down':  ChevronDown,
  'chevron-left':  ChevronLeft,
  'chevron-right': ChevronRight,
  'circle':        Circle,
  'clock':         Clock,
  'cloud':         Cloud,
  'compass':       Compass,
  'crop':          Crop,
  'droplet':       Droplet,
  'edit-2':        Pencil,
  'eye':           Eye,
  'eye-off':       EyeOff,
  'feather':       Feather,
  'file-text':     FileText,
  'flag':          Flag,
  'globe':         Globe,
  'grid':          Grid3x3,
  'heart':         Heart,
  'home':          Home,
  'image':         ImageIcon,
  'key':           Key,
  'layers':        Layers,
  'layout':        LayoutGrid,
  'lock':          Lock,
  'log-out':       LogOut,
  'mail':          Mail,
  'map-pin':       MapPin,
  'maximize-2':    Maximize2,
  'message-circle': MessageCircle,
  'minus':         Minus,
  'monitor':       Monitor,
  'moon':          Moon,
  'plus':          Plus,
  'plus-circle':   CirclePlus,
  'refresh-cw':    RefreshCw,
  'search':        Search,
  'send':          Send,
  'settings':      Settings,
  'shield':        Shield,
  'slash':         Slash,
  'sliders':       SlidersHorizontal,
  'smile':         Smile,
  'star':          Star,
  'sun':           Sun,
  'sunrise':       Sunrise,
  'trash-2':       Trash2,
  'trending-up':   TrendingUp,
  'user':          User,
  'users':         Users,
  'wind':          Wind,
  'x':             X,
  'zap':           Zap,
} as const;

export type IconName = keyof typeof ICON_MAP;

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName | string;
  size?: number;
  color?: string;
}

export function Icon({ name, size = 20, color = '#000', style, ...rest }: IconProps) {
  const Component = ICON_MAP[name as IconName];
  if (!Component) return null;
  return <Component size={size} color={color} style={style} {...rest} />;
}
