import i18n from 'i18next';

// Drawer-specific strings merged into each language's existing `social`
// namespace. Existing keys are never overwritten (overwrite=false).
type Strings = {
  openMessages: string; closeDrawer: string; newMessage: string; chooseRecipient: string; cancelNewMessage: string;
  searchMessagesPlaceholder: string; received: string; sent: string; unavailable: string; unavailableBody: string;
  conversationsLoadError: string; unreadCount: string; unreadConversation: string; noContacts: string;
  noContactsMatch: string; offlineNotice: string; pickerEmpty: string;
};
export const DRAWER_STRINGS: Record<string, Strings> = {
  en: { openMessages: 'Open messages and friends', closeDrawer: 'Close messages', newMessage: 'New message', chooseRecipient: 'Choose who to message', cancelNewMessage: 'Cancel new message', searchMessagesPlaceholder: 'Search by name or @username', received: 'Received', sent: 'Sent', unavailable: 'Messaging unavailable', unavailableBody: 'Your account cannot access friends and messages right now.', conversationsLoadError: 'Could not load recent conversations.', unreadCount: '{{count}} unread', unreadConversation: 'Unread conversation', noContacts: 'No friends or conversations yet. Tap Add Friends to find people.', noContactsMatch: 'No contacts match your search.', offlineNotice: 'You appear to be offline.', pickerEmpty: 'Add a friend first to start a conversation.' },
  es: { openMessages: 'Abrir mensajes y amigos', closeDrawer: 'Cerrar mensajes', newMessage: 'Mensaje nuevo', chooseRecipient: 'Elige a quién escribir', cancelNewMessage: 'Cancelar mensaje nuevo', searchMessagesPlaceholder: 'Buscar por nombre o @usuario', received: 'Recibidas', sent: 'Enviadas', unavailable: 'Mensajes no disponibles', unavailableBody: 'Tu cuenta no puede acceder a amigos ni mensajes ahora.', conversationsLoadError: 'No se pudieron cargar las conversaciones recientes.', unreadCount: '{{count}} sin leer', unreadConversation: 'Conversación sin leer', noContacts: 'Aún no hay amigos ni conversaciones. Toca Añadir amigos.', noContactsMatch: 'Ningún contacto coincide con tu búsqueda.', offlineNotice: 'Parece que no tienes conexión.', pickerEmpty: 'Añade primero un amigo para iniciar una conversación.' },
  fr: { openMessages: 'Ouvrir messages et amis', closeDrawer: 'Fermer les messages', newMessage: 'Nouveau message', chooseRecipient: 'Choisissez un destinataire', cancelNewMessage: 'Annuler le nouveau message', searchMessagesPlaceholder: 'Rechercher par nom ou @pseudo', received: 'Reçues', sent: 'Envoyées', unavailable: 'Messagerie indisponible', unavailableBody: "Votre compte ne peut pas accéder aux amis et messages pour le moment.", conversationsLoadError: 'Impossible de charger les conversations récentes.', unreadCount: '{{count}} non lus', unreadConversation: 'Conversation non lue', noContacts: "Aucun ami ni conversation. Touchez Ajouter des amis.", noContactsMatch: 'Aucun contact ne correspond.', offlineNotice: 'Vous semblez hors ligne.', pickerEmpty: 'Ajoutez d’abord un ami pour discuter.' },
  de: { openMessages: 'Nachrichten und Freunde öffnen', closeDrawer: 'Nachrichten schließen', newMessage: 'Neue Nachricht', chooseRecipient: 'Empfänger wählen', cancelNewMessage: 'Neue Nachricht abbrechen', searchMessagesPlaceholder: 'Nach Name oder @Benutzername suchen', received: 'Erhalten', sent: 'Gesendet', unavailable: 'Nachrichten nicht verfügbar', unavailableBody: 'Dein Konto kann derzeit nicht auf Freunde und Nachrichten zugreifen.', conversationsLoadError: 'Letzte Unterhaltungen konnten nicht geladen werden.', unreadCount: '{{count}} ungelesen', unreadConversation: 'Ungelesene Unterhaltung', noContacts: 'Noch keine Freunde oder Unterhaltungen. Tippe auf Freunde hinzufügen.', noContactsMatch: 'Keine Kontakte gefunden.', offlineNotice: 'Du scheinst offline zu sein.', pickerEmpty: 'Füge zuerst einen Freund hinzu.' },
  it: { openMessages: 'Apri messaggi e amici', closeDrawer: 'Chiudi messaggi', newMessage: 'Nuovo messaggio', chooseRecipient: 'Scegli a chi scrivere', cancelNewMessage: 'Annulla nuovo messaggio', searchMessagesPlaceholder: 'Cerca per nome o @username', received: 'Ricevute', sent: 'Inviate', unavailable: 'Messaggi non disponibili', unavailableBody: 'Il tuo account non può accedere ad amici e messaggi al momento.', conversationsLoadError: 'Impossibile caricare le conversazioni recenti.', unreadCount: '{{count}} non letti', unreadConversation: 'Conversazione non letta', noContacts: 'Ancora nessun amico o conversazione. Tocca Aggiungi amici.', noContactsMatch: 'Nessun contatto corrisponde.', offlineNotice: 'Sembra che tu sia offline.', pickerEmpty: 'Aggiungi prima un amico per iniziare.' },
  pt: { openMessages: 'Abrir mensagens e amigos', closeDrawer: 'Fechar mensagens', newMessage: 'Nova mensagem', chooseRecipient: 'Escolha para quem escrever', cancelNewMessage: 'Cancelar nova mensagem', searchMessagesPlaceholder: 'Buscar por nome ou @usuário', received: 'Recebidos', sent: 'Enviados', unavailable: 'Mensagens indisponíveis', unavailableBody: 'Sua conta não pode acessar amigos e mensagens agora.', conversationsLoadError: 'Não foi possível carregar as conversas recentes.', unreadCount: '{{count}} não lidas', unreadConversation: 'Conversa não lida', noContacts: 'Ainda sem amigos ou conversas. Toque em Adicionar amigos.', noContactsMatch: 'Nenhum contato corresponde.', offlineNotice: 'Você parece estar offline.', pickerEmpty: 'Adicione um amigo primeiro.' },
  tr: { openMessages: 'Mesajları ve arkadaşları aç', closeDrawer: 'Mesajları kapat', newMessage: 'Yeni mesaj', chooseRecipient: 'Kime yazacağını seç', cancelNewMessage: 'Yeni mesajı iptal et', searchMessagesPlaceholder: 'Ad veya @kullanıcı adıyla ara', received: 'Alınan', sent: 'Gönderilen', unavailable: 'Mesajlaşma kullanılamıyor', unavailableBody: 'Hesabın şu anda arkadaşlara ve mesajlara erişemiyor.', conversationsLoadError: 'Son sohbetler yüklenemedi.', unreadCount: '{{count}} okunmamış', unreadConversation: 'Okunmamış sohbet', noContacts: 'Henüz arkadaş veya sohbet yok. Arkadaş Ekle’ye dokun.', noContactsMatch: 'Aramanla eşleşen kişi yok.', offlineNotice: 'Çevrimdışı görünüyorsun.', pickerEmpty: 'Önce bir arkadaş ekle.' },
  ru: { openMessages: 'Открыть сообщения и друзей', closeDrawer: 'Закрыть сообщения', newMessage: 'Новое сообщение', chooseRecipient: 'Выберите получателя', cancelNewMessage: 'Отменить новое сообщение', searchMessagesPlaceholder: 'Поиск по имени или @нику', received: 'Полученные', sent: 'Отправленные', unavailable: 'Сообщения недоступны', unavailableBody: 'Ваш аккаунт сейчас не может открыть друзей и сообщения.', conversationsLoadError: 'Не удалось загрузить недавние диалоги.', unreadCount: 'Непрочитано: {{count}}', unreadConversation: 'Непрочитанный диалог', noContacts: 'Пока нет друзей и диалогов. Нажмите «Добавить друзей».', noContactsMatch: 'Контакты не найдены.', offlineNotice: 'Похоже, вы не в сети.', pickerEmpty: 'Сначала добавьте друга.' },
  ar: { openMessages: 'فتح الرسائل والأصدقاء', closeDrawer: 'إغلاق الرسائل', newMessage: 'رسالة جديدة', chooseRecipient: 'اختر المستلم', cancelNewMessage: 'إلغاء الرسالة الجديدة', searchMessagesPlaceholder: 'ابحث بالاسم أو @اسم المستخدم', received: 'المستلمة', sent: 'المرسلة', unavailable: 'المراسلة غير متاحة', unavailableBody: 'لا يمكن لحسابك الوصول إلى الأصدقاء والرسائل حاليًا.', conversationsLoadError: 'تعذر تحميل المحادثات الأخيرة.', unreadCount: '{{count}} غير مقروءة', unreadConversation: 'محادثة غير مقروءة', noContacts: 'لا أصدقاء ولا محادثات بعد. اضغط إضافة أصدقاء.', noContactsMatch: 'لا توجد جهات اتصال مطابقة.', offlineNotice: 'يبدو أنك غير متصل.', pickerEmpty: 'أضف صديقًا أولًا.' },
  ja: { openMessages: 'メッセージとフレンドを開く', closeDrawer: 'メッセージを閉じる', newMessage: '新規メッセージ', chooseRecipient: '送信相手を選択', cancelNewMessage: '新規メッセージをキャンセル', searchMessagesPlaceholder: '名前または@ユーザー名で検索', received: '受信', sent: '送信済み', unavailable: 'メッセージを利用できません', unavailableBody: '現在このアカウントではフレンドとメッセージにアクセスできません。', conversationsLoadError: '最近の会話を読み込めませんでした。', unreadCount: '未読{{count}}件', unreadConversation: '未読の会話', noContacts: 'フレンドも会話もまだありません。「フレンドを追加」をタップ。', noContactsMatch: '一致する連絡先がありません。', offlineNotice: 'オフラインのようです。', pickerEmpty: 'まずフレンドを追加してください。' },
  ko: { openMessages: '메시지 및 친구 열기', closeDrawer: '메시지 닫기', newMessage: '새 메시지', chooseRecipient: '받는 사람 선택', cancelNewMessage: '새 메시지 취소', searchMessagesPlaceholder: '이름 또는 @아이디로 검색', received: '받은 요청', sent: '보낸 요청', unavailable: '메시지를 사용할 수 없음', unavailableBody: '지금은 계정으로 친구와 메시지에 접근할 수 없어요.', conversationsLoadError: '최근 대화를 불러오지 못했어요.', unreadCount: '읽지 않음 {{count}}', unreadConversation: '읽지 않은 대화', noContacts: '아직 친구나 대화가 없어요. 친구 추가를 눌러보세요.', noContactsMatch: '검색과 일치하는 연락처가 없어요.', offlineNotice: '오프라인 상태인 것 같아요.', pickerEmpty: '먼저 친구를 추가하세요.' },
  zh: { openMessages: '打开消息与好友', closeDrawer: '关闭消息', newMessage: '新消息', chooseRecipient: '选择收件人', cancelNewMessage: '取消新消息', searchMessagesPlaceholder: '按名称或 @用户名搜索', received: '收到的', sent: '已发送', unavailable: '消息功能不可用', unavailableBody: '你的账号目前无法访问好友和消息。', conversationsLoadError: '无法加载最近的对话。', unreadCount: '{{count}} 条未读', unreadConversation: '未读对话', noContacts: '还没有好友或对话。点按“添加好友”。', noContactsMatch: '没有匹配的联系人。', offlineNotice: '你似乎已离线。', pickerEmpty: '请先添加好友。' },
};

export function registerDrawerTranslations(): void {
  const langs = Object.keys(i18n.options?.resources ?? { en: 1 });
  for (const lng of langs) {
    const strings = DRAWER_STRINGS[lng] ?? DRAWER_STRINGS.en;
    i18n.addResourceBundle(lng, 'translation', { social: strings }, true, false);
  }
}
registerDrawerTranslations();
