// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sky-reimagine/DreamyPastel.tsx": () => import("../components/mockups/sky-reimagine/DreamyPastel.tsx"),
  "./components/mockups/sky-reimagine/PaperCrane.tsx": () => import("../components/mockups/sky-reimagine/PaperCrane.tsx"),
  "./components/mockups/sky-reimagine/StardustNight.tsx": () => import("../components/mockups/sky-reimagine/StardustNight.tsx"),
  "./components/mockups/home-redesign/CampfireWorld.tsx": () => import("../components/mockups/home-redesign/CampfireWorld.tsx"),
  "./components/mockups/home-redesign/Celestial.tsx": () => import("../components/mockups/home-redesign/Celestial.tsx"),
  "./components/mockups/home-redesign/ConstellationSky.tsx": () => import("../components/mockups/home-redesign/ConstellationSky.tsx"),
  "./components/mockups/home-redesign/Minimal.tsx": () => import("../components/mockups/home-redesign/Minimal.tsx")
};
